"""add last_article_sent_at to user

Revision ID: 107ce90511d5
Revises: 2da9033ef4f2
Create Date: 2026-04-12 21:08:47.485630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107ce90511d5'
down_revision: Union[str, Sequence[str], None] = '2da9033ef4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_article_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_last_article_sent_at'), 'users', ['last_article_sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_article_sent_at'), table_name='users')
    op.drop_column('users', 'last_article_sent_at')
    # ### end Alembic commands ###
